use_frameworks!
platform :ios, '11.0'

target 'ImageStore_Example' do
    pod 'ImageStore', path: '../'

  target 'ImageStore_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
